column = ['Дата закрытия', 'ID Сделки', 'Источник трафика', 'gnzs_docflow', 'UTM Source',
          'Связанные сделки', 'Вопрос клиента', 'TEXT', 'REFERER', 'COOKIES', 'FORMNAME', 'TRANID', 'FORMID',
          'SELECTBOX', 'Полное имя контакта', 'Компания контакта', "Ответственный за контакт",
          'КАКИЕ_ДОПОЛНИТЕЛЬНЫЕ_ПОМЕЩЕНИЯ_ТРЕБУЮТСЯ', 'КАКАЯ_ОБЩАЯ_ПЛОЩАДЬ_ГОСТИНИЦЫ',
          'СКОЛЬКО_ЗВЁЗД_ПЛАНИРУЕТСЯ', 'КАКОЕ_КОЛИЧЕСТВО_НОМЕРОВ_ПЛАНИРУЕТСЯ', 'utm_source', 'utm_campaign',
          'openstat_service', 'fbclid', 'yclid', 'gclid', 'gclientid', 'from', 'openstat_source', 'openstat_ad',
          'openstat_campaign', 'roistat', '_ym_counter', '_ym_uid', 'utm_referrer', 'utm_content', 'utm_source',
          'referrer', 'utm_medium', 'utm_campaign', 'utm_term', 'ga_utm', 'Должность',
          'Рабочий email', 'Личный email', 'Другой email', 'Рабочий телефон',
          'Рабочий прямой телефон', 'Мобильный телефон', 'Факс',
          'Домашний телефон', 'Другой телефон', 'Skype', 'ICQ',
          'Jabber', 'Google Talk', 'MSN', 'Другой IM', 'Компания.1', 'Источник лида.1',
          'Источник трафика', 'Источник трафика.1', 'Трекинг', 'Канал Callibri', 'Яндекс ClientID',
          'Ссылка на карту', 'Номер карты', 'Часовой пояс.1', 'Источник лида',
          'ip', 'utm_source.1', 'utm_source.2', 'utm_content', 'utm_content.1', 'utm_medium', 'utm_medium.1',
          'utm_campaign.1', 'utm_campaign.2', 'utm_term.1',
          'utm_campaign', 'utm_term', 'Источник', 'CPC', 'Компания',
          'Ключевая фраза', 'google client id', 'Keyword',
          'Пользовательское соглашение', 'Примечание', 'Примечание 2', 'Примечание 3', 'Примечание 4', 'Примечание 5']
